### ISSUE TITLE
Internal Error - Generating report

### ISSUE THREAD

**Issue by Dexvar** [UndeadSec/SocialFish#119]
I'm getting an "Internal Error" when generating a report. Here's what the console outputs during the error: 

```
192.168.76.50 - - [18/Mar/2019 17:12:24] "GET /report HTTP/1.1" 200 -
[(1, 'https://github.com/login', "{'commit': 'Sign in', 'utf8': '✓', 'authenticity_token': '3mAUofM6R8bHTE+x7ruW8Gf8mVCK+Xiv9hkGDhfYWA7JvVItzq/Uw6jZo3Le53N+NTSwHQ1D8sPOzu2K8ytgZQ==', 'login': 'RobZombie', 'password': '$ickBubblegum'}", '03-18-2019', 'chrome', '73.0.3683.75', 'windows', '192.168.76.50'), (2, 'https://www.facebook.com/login.php', "{'jazoest': '2752', 'lsd': 'AVph_rcM', 'display': '', 'enable_profile_selector': '', 'isprivate': '', 'legacy_return': '0', 'profile_selector_ids': '', 'return_session': '', 'skip_api_login': '', 'signed_next': '', 'trynum': '1', 'timezone': '-60', 'lgndim': 'eyJ3IjoxMzY2LCJoIjo3NjgsImF3IjoxMzY2LCJhaCI6NzI4LCJjIjoyNH0=', 'lgnrnd': '081051_9Oae', 'lgnjs': '1552921891', 'email': 'Electric_Warlock', 'pass': 'AcidWitch27', 'prefill_contact_point': '', 'prefill_source': '', 'prefill_type': '', 'first_prefill_source': '', 'first_prefill_type': '', 'had_cp_prefilled': 'false', 'had_password_prefilled': 'false', 'ab_test_data': 'fA/f/f/APPPPPPAAAPAAPAAAAAAAAAAAAAAAAAAA/ddEEAAAAANBAa'}", '03-18-2019', 'chrome', '73.0.3683.75', 'windows', '192.168.76.50'), (3, 'https://github.com/login', "{'commit': 'Sign in', 'utf8': '✓', 'authenticity_token': 'HrIFe2QKUXbMZfhmCDWHShpuXtVnhYvqWi1wqsVQP/BUP4x0+975Fk+CU/TqaMe1tpr9+66og59Ihkl+e05xzQ==', 'login': 'alberto_morales@gmail.com', 'password': 'MICONTRASEÑA'}", '03-18-2019', 'chrome', '73.0.3683.75', 'windows', '192.168.76.50'), (4, 'https://github.com/login', "{'commit': 'Sign in', 'utf8': '✓', 'authenticity_token': 'HrIFe2QKUXbMZfhmCDWHShpuXtVnhYvqWi1wqsVQP/BUP4x0+975Fk+CU/TqaMe1tpr9+66og59Ihkl+e05xzQ==', 'login': 'mik', 'password': 'test'}", '03-18-2019', 'chrome', '73.0.3683.75', 'windows', '192.168.76.50'), (5, 'https://github.com/login', "{'commit': 'Sign in', 'utf8': '✓', 'authenticity_token': 'VndDyngEABp7dzavXNvmmi2WoMXQVt7Oz+jx+CjGQFqiEujBLtwfNqIWVkE72ubuS3hWCDdqFvhAB7QGFDaJ4g==', 'login': 'test', 'password': '123456'}", '03-18-2019', 'chrome', '73.0.3683.75', 'windows', '192.168.76.50')]
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./Report-1903.tex
LaTeX2e <2018-12-01>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)
kpathsea: Running mktextfm ecrm1000
/usr/share/texlive/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for ecrm1000.
/usr/share/texlive/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input ecrm1000
This is METAFONT, Version 2.7182818 (TeX Live 2019/dev/Debian) (preloaded base=mf)

kpathsea: Running mktexmf ecrm1000

! I can't find file `ecrm1000'.
<*> ...ljfour; mag:=1; nonstopmode; input ecrm1000
                                                  
Please type another input file name
! Emergency stop.
<*> ...ljfour; mag:=1; nonstopmode; input ecrm1000
                                                  
Transcript written on mfput.log.
grep: ecrm1000.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input ecrm1000' failed to make ecrm1000.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file not fou
nd.
<to be read again> 
                   relax 
l.105 \fontencoding\encodingdefault\selectfont
                                              
) (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/share/texmf/tex/latex/lm/lmodern.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))

! LaTeX Error: File `lastpage.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7 \usepackage
               [head=60pt,margin=0.5in,bottom=0.6in,includeheadfoot=True]{ge...

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Report-1903.log.

[2019-03-18 17:12:36,419] ERROR in app: Exception on /report [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "SocialFish.py", line 302, in getReport
    generate_unique(DATABASE,_target)
  File "/root/Desktop/SocialFish/core/report.py", line 110, in generate_unique
    doc.generate_pdf(pdf_name, clean_tex=False)
  File "/usr/local/lib/python3.7/dist-packages/pylatex/document.py", line 233, in generate_pdf
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pdflatex', '--interaction=nonstopmode', 'Report-1903.tex']' returned non-zero exit status 1.
```
It seems the reports have been generated though, what might be going wrong?

**Comment by A1S0N** [comment]
Hello,
We are looking for the problem resolution.

Thanks by reporting.

**Comment by Dexvar** [comment]
> Hello,
> We are looking for the problem resolution.
> 
> Thanks by reporting.

Hey, any updates on this?

**Comment by Dexvar** [comment]
> Hello,
> We are looking for the problem resolution.
> 
> Thanks by reporting.

Hey, any updates on this?

**Comment by A1S0N** [comment]
@Dexvar We cannot reproduce the occurrence, do it stills going wrong?

**Comment by Dexvar** [comment]
> @Dexvar We cannot reproduce the occurrence, do it stills going wrong?

I tried a few days ago and it still happened. Let me check again and if I can replicate the issue I'll try and record a video to show you.
