### ISSUE TITLE
Nameerror : name 'SocialFish' is not defined

### ISSUE THREAD

**Issue by mathieu82100** [UndeadSec/SocialFish#138]
Hello,

I had a unicode error ( the same in the issue #111 ) I tried to erase the ascii code and put SocialFish as recommended.

Now when I try : python3 socialfish.py math123 passwd123 I have : 

Traceback (most recent call last):
  File "SocialFish.py", line 537, in <module>
    main()
  File "SocialFish.py", line 529, in main
    head()
  File "/root/newSP/socialfish/core/view.py", line 4, in head
    print(SocialFish)
NameError: name 'SocialFish' is not defined

Someone have an idea ?

**Comment by A1S0N** [comment]
You forgot the `"`

`print('SocialFish')`
