### ISSUE TITLE
Why Did you closed an unsolved issue ? Issue with parrot sec os

### ISSUE THREAD

**Issue by SheesAli** [UndeadSec/SocialFish#14]
When I am pressing 2 for " Advanced Phishing(poll_mode/login_with) " It is showing following error:

Traceback (most recent call last):
File "SocialFish.py", line 184, in 
runNgrok()
File "SocialFish.py", line 175, in runNgrok
print('\n {0}[{1}*{0}]{1} Ngrok URL: {2}' + url.readlines()[0] + '{1}').format(CYAN, END, GREEN)
IndexError: list index out of range

**Comment by djtroby** [comment]
When I am pressing 2 for " Advanced Phishing(poll_mode/login_with) " It is showing following error:

Traceback (most recent call last):
File "SocialFish.py", line 184, in
runNgrok()
File "SocialFish.py", line 175, in runNgrok
print('\n {0}[{1}*{0}]{1} Ngrok URL: {2}' + url.readlines()[0] + '{1}').format(CYAN, END, GREEN)
IndexError: list index out of range

**Comment by A1S0N** [comment]
Please try to clone and run again now.

**Comment by djtroby** [comment]
Hi there....now getting this error

sh: 1: ./Server/ngrok: Exec format error

 [*] Ngrok URL:
 [*] Waiting for credentials...

PHP 7.2.1-1 Development Server started at Fri Feb  9 05:04:52 2018
Listening on http://127.0.0.1:80
Document root is /root/SocialFish/Server/www
Press Ctrl-C to quit.

Please confirm if it can be run over SSH and is ARM (RPi-3) compatible.
BTW works like charm in Kali VM

**Comment by A1S0N** [comment]
Because you're using ARM. Please wait until tonight, a version with ARM support will be released.

**Comment by djtroby** [comment]
Ohh thats great.....appreciate your support.

**Comment by djtroby** [comment]
Any solution for ngrok to work via internet .....it does work on intranet....please help

**Comment by djtroby** [comment]
Any hacking solution for whatsapp or recommendation

**Comment by SheesAli** [comment]
Ngrok have issues with Parrot Sec OS now I am using Kali Linux and both ngrok and social fish is running fine.
