### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by th1051xrt** [UndeadSec/SocialFish#155]
Hi . please excuse my translation, I have the following error, I can not find it. Can they indicate that I am doing wrong? Thank you
I have performed the procedure as indicated, in another machine Kali works perfect.

Go to http://0.0.0.0:5000/neptune to start
Traceback (most recent call last):
  File "SocialFish.py", line 537, in <module>
    main()
  File "SocialFish.py", line 532, in main
    initDB(DATABASE)
  File "/home/prometeo/ataque/SocialFish/core/dbsf.py", line 7, in initDB
    conn = sqlite3.connect(DATABASE)
sqlite3.OperationalError: unable to open database file

use debian 9.9, python 3.6.4 , sqlite3

**Comment by Floo33R** [comment]
You can try this:
`sudo su`
`python3 SocialFish.py "YOUR_USERNAME" "YOUR_PASSWORD"`

**Comment by pacomedanilo** [comment]
no this commande no start and no strat with cd SocialFish

**Comment by Alinaahmad** [comment]
@Floo33R Running that as a superuser still throws error as attached 
```
Traceback (most recent call last):
  File "SocialFish.py", line 3, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/usr/lib/python3/dist-packages/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package
```
