### ISSUE TITLE
Adress invalid

### ISSUE THREAD

**Issue by j-dogcoder** [UndeadSec/SocialFish#245]
When I navigate to http://0.0.0.0:5000/neptune, I see "This site can’t be reached. 0.0.0.0 refused to connect.". I ran ython3 SocialFish.py with my username and passcode and received this. `pi@ServerPi:~/SocialFish $ python3 SocialFish.py Jasper test

                          '
                        '   '  UNDEADSEC | t.me/UndeadSec 
                      '       '  youtube.com/c/UndeadSec - BRAZIL
                 .  '  .        '                        '
             '             '      '                   '   '
  ███████ ████████ ███████ ██ ███████ ██       ███████ ██ ███████ ██   ██ 
  ██      ██    ██ ██      ██ ██   ██ ██       ██      ██ ██      ██   ██ 
  ███████ ██    ██ ██      ██ ███████ ██       █████   ██ ███████ ███████ 
       ██ ██    ██ ██      ██ ██   ██ ██       ██      ██      ██ ██   ██ 
  ███████ ████████ ███████ ██ ██   ██ ███████  ██      ██ ███████ ██   ██ 
      .    '   '....'               ..'.      ' .
         '  .                     .     '          '     '  v3.0Nepture
               '  .  .  .  .  . '.    .'              '  .
                   '         '    '. '      Twitter: https://twitter.com/A1S0N_
                     '       '      '       Site: https://www.undeadsec.com
                       ' .  '
                           
Go to http://0.0.0.0:5000/neptune to start
 * Serving Flask app "SocialFish" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "SocialFish.py", line 540, in <module>
    main()
  File "SocialFish.py", line 536, in main
    app.run(host="0.0.0.0", port=5000)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/home/pi/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/pi/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/home/pi/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/pi/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
pi@ServerPi:~/SocialFish $ 
`

**Comment by krzysko** [comment]
OSError: [Errno 98] Address already in use

**Comment by pray4mercyx** [comment]
is there a fix for that? i cant reach the page either

**Comment by yzz-bear** [comment]
> OSError：[Errno 98]地址已在使用中

是的
