### ISSUE TITLE
Error on starup!! pls help

### ISSUE THREAD

**Issue by Historical-17** [UndeadSec/SocialFish#368]
Traceback (most recent call last):
  File "socialfish.py", line 543, in <module>
    main()
  File "socialfish.py", line 535, in main
    head()
  File "C:\Users\Madsands\Desktop\▒▒▒▒▒\Tools\SocialFish-3.0.0\core\view.py", line 5, in head
    print(colorama.Fore.CYAN + '''
  File "C:\Users\Madsands\AppData\Local\Programs\Python\Python38\lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 286-292: character maps to <undefined>

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
