### ISSUE TITLE
Help, I have a problem

### ISSUE THREAD

**Issue by minibox161** [UndeadSec/SocialFish#58]
File "SocialFish.py", line 35, in <module>
    from core.phishingRunner import *
  File "C:\Users\admin\Desktop\SocialFish-master\core\phishingRunner.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by minibox161** [comment]
[*] Downloading Ngrok...
Traceback (most recent call last):
  File "SocialFish.py", line 105, in <module>
    pre()
  File "C:\Users\admin\Desktop\SocialFish-master\core\pre.py", line 52, in pre
    checkNgrok()
  File "C:\Users\admin\Desktop\SocialFish-master\core\pre.py", line 30, in checkNgrok
    if 'Android' in str(check_output(('uname', '-a'))):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)

**Comment by minibox161** [comment]
again error

**Comment by A1S0N** [comment]
It is not an error, you are running SF on Windows. SocialFish does not support that.
