### ISSUE TITLE
again a mistake, what should I do?

### ISSUE THREAD

**Issue by minibox161** [UndeadSec/SocialFish#59]
[*] Downloading Ngrok...
Traceback (most recent call last):
File "SocialFish.py", line 105, in
pre()
File "C:\Users\admin\Desktop\SocialFish-master\core\pre.py", line 52, in pre
checkNgrok()
File "C:\Users\admin\Desktop\SocialFish-master\core\pre.py", line 30, in checkNgrok
if 'Android' in str(check_output(('uname', '-a'))):
File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 376, in check_output
**kwargs).stdout
File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 453, in run
with Popen(*popenargs, **kwargs) as process:
File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 756, in init
restore_signals, start_new_session)
File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1155, in _execute_child
startupinfo)

**Comment by A1S0N** [comment]
It is not an error. SF does not support that.
