### ISSUE TITLE
Got a problem with building site

### ISSUE THREAD

**Issue by gsadga** [UndeadSec/SocialFish#69]
[*] vk module loaded. Building site...
Traceback (most recent call last):
  File "SocialFish.py", line 68, in <module>
    PhishingServer()
  File "/home/pi/SocialFish/core/phishingRunner.py", line 91, in PhishingServer
    with ngrok_start(port) as ngrok:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/SocialFish/core/phishingRunner.py", line 73, in ngrok_start
    stderr=subprocess.PIPE
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
--------
Help pls!!!!

**Comment by A1S0N** [comment]
Can you please try python 3.6?

**Comment by gsadga** [comment]
> Can you please try python 3.6?

It doesn't work too

**Comment by gsadga** [comment]
> Can you please try python 3.6?

File "SocialFish.py", line 68, in <module>
    PhishingServer()
  File "/home/pi/SocialFish/core/phishingRunner.py", line 91, in PhishingServer
    with ngrok_start(port) as ngrok:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/pi/SocialFish/core/phishingRunner.py", line 73, in ngrok_start
    stderr=subprocess.PIPE
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './base/Server/ngrok'

**Comment by miqbalnawaz** [comment]
Its not work on social media 
When i press (s) its not show anything

**Comment by A1S0N** [comment]
Updated
