### ISSUE TITLE
python doesn't work

### ISSUE THREAD

**Issue by BiZken** [UndeadSec/SocialFish#74]
So I'm trying to use Social fish but it wont work, 
so im typing in python3 Socialfish.py and then this comes:

root@kali:~/Desktop/SocialFish# python3 SocialFish.py 
Traceback (most recent call last):
  File "SocialFish.py", line 25, in <module>
    from core.view import *
  File "/root/Desktop/SocialFish/core/view.py", line 14, in <module>
    from huepy import *
ModuleNotFoundError: No module named 'huepy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SocialFish.py", line 28, in <module>
    import pip
ModuleNotFoundError: No module named 'pip'

what should I Do?
plz help

**Comment by A1S0N** [comment]
sudo apt-get install python3-pip
