### ISSUE TITLE
SocialFish Error

### ISSUE THREAD

**Issue by sTiKyt** [UndeadSec/SocialFish#82]
[stikyt@stikyt SocialFish]$ sudo socialfish
which: no php in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Traceback (most recent call last):
  File "SocialFish.py", line 66, in <module>
    pre()
  File "/usr/share/socialfish/core/pre.py", line 61, in pre
    if checkPHP() == False:
  File "/usr/share/socialfish/core/pre.py", line 52, in checkPHP
    if 256 != check_output(['which', 'php']):
  File "/usr/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'php']' returned non-zero exit status 1.

Without sudo - same.

**Comment by tatsuryu** [comment]
This error is because php binaries are not present. Please install php first.
