### ISSUE TITLE
Its not working now

### ISSUE THREAD

**Issue by Dodo0606** [UndeadSec/SocialFish#90]
Hi undead sec its not working now please fix it

**Comment by pachinko2821** [comment]
hey UndeadSec, I get the following error when the program tries to "Build the site" :

touch: cannot touch 'base/Server/www/cat.txt': No such file or directory
cp: cannot stat 'base/WebPages/instagram/*.*': No such file or directory
Traceback (most recent call last):
  File "/root/SocialFish/SocialFish.py", line 67, in <module>
    main()
  File "/root/SocialFish/SocialFish.py", line 62, in main
    runPhishing(site.lower(), custom)
  File "/root/SocialFish/core/phishingRunner.py", line 32, in runPhishing
    with open('base/Server/www/login.php') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'base/Server/www/login.php'
