### ISSUE TITLE
NEED Help ASAP 

### ISSUE THREAD

**Issue by Scumpunk** [UndeadSec/SocialFish#93]
FYI python updated 
Traceback (most recent call last):
  File "SocialFish.py", line 25, in <module>
    from core.view import *
  File "/opt/SocialFish/core/view.py", line 14, in <module>
    from huepy import *
ModuleNotFoundError: No module named 'huepy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SocialFish.py", line 28, in <module>
    import pip
ModuleNotFoundError: No module named 'pip'

**Comment by finnfassnacht** [comment]
same problem !!
